spring:
  profiles:
    active: dev

server:
  port: 8081
  
--- 

spring:
  profiles: dev
  
rest:
  greeting: test hello
  
datasource:
  rest:
    jdbc-url: jdbc:mysql://localhost:3306/rest?autoReconnect=true&useSSL=false
    username: rest
    password: rest
    driver-class-name: com.mysql.jdbc.Driver
    minimum-idle: 2
    maximum-pool-size: 5
    auto-commit: false
    connection-test-query: SELECT 1
  log:
    jdbc-url: jdbc:mysql://localhost:3306/rest_log?autoReconnect=true&useSSL=false
    username: rest
    password: rest
    driver-class-name: com.mysql.jdbc.Driver
    minimum-idle: 2
    maximum-pool-size: 5
    auto-commit: false
    connection-test-query: SELECT 1
    
---

spring:
  profiles: live
  
rest:
  greeting: hello

datasource:
  rest:
    jdbc-url: jdbc:mysql://localhost:3306/rest?autoReconnect=true&useSSL=false
    username: rest
    password: rest
    driver-class-name: com.mysql.jdbc.Driver
    minimum-idle: 2
    maximum-pool-size: 5
    auto-commit: false
    connection-test-query: SELECT 1
  log:
    jdbc-url: jdbc:mysql://localhost:3306/rest_log?autoReconnect=true&useSSL=false
    username: rest
    password: rest
    driver-class-name: com.mysql.jdbc.Driver
    minimum-idle: 2
    maximum-pool-size: 5
    auto-commit: false
    connection-test-query: SELECT 1